lsst/ctrl_bps

- python/lsst/ctrl/bps/bps_config.py
The dictionary passed to the class constructor was expected to have the actual config values themselves, but rather provide information about how to construct the config, e.g., location of the config file.  I modified the constructor to allow one to pass in a dictionary of values.
> DM-26844: Make BpsConfig accept dictionary of values

- doc/changes/DM-31859.feature.rst
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/bps_config.py
- python/lsst/ctrl/bps/bps_utils.py
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- python/lsst/ctrl/bps/report.py
- python/lsst/ctrl/bps/transform.py
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/wms/htcondor/lssthtc.py
Pushing code changes so others can see/try.  Still working on doc changes.
> DM-31859: Add first version of user-defined clustering.

- doc/changes/DM-32074.bugfix.rst
- doc/changes/DM-32074.feature.rst
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
> DM-32074:  Modify how HTCondor plugin handles transfer of execution butler

- doc/changes/DM-32201.bugfix.rst
- doc/changes/DM-32201.misc.rst
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
> DM-32201-v23: HTCondor plugin bug if output collection contains period

- doc/changes/DM-32241.bugfix.rst
- doc/changes/DM-32241.perf.rst
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- python/lsst/ctrl/bps/transform.py
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
> DM-32241: Cache config values repeated per label.

- doc/changes/DM-32435.bugfix.rst
- python/lsst/ctrl/bps/wms/panda/edgenode/cmd_line_decoder.py
added a file to the doc/changes directory
> Implemented propagation of pipetask kill by signal

- doc/changes/DM-32066.bugfix.rst
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
> DM-32066-v23: BPS jobs with memory autoscaling enabled remain idle after the first run attempt

- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
- python/lsst/ctrl/bps/wms/panda/conf_example/example_panda_SLAC.yaml
> DM-31976: (v23) Add register-dataset-types to transfer-datasets command

- doc/changes/DM-32241.bugfix.rst
- doc/changes/DM-32241.perf.rst
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- python/lsst/ctrl/bps/transform.py
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
> DM-32241-v23: bps submit can take multiple hours

- doc/changes/DM-32695.misc.rst
- python/lsst/ctrl/bps/wms/panda/conf_example/pipelines_check_idf.yaml
> DM-32695: Make PanDA's IDF example more readily for a test run on data-int

- config/bps_idf.yaml
- doc/changes/DM-32594.other.rst
- python/lsst/ctrl/bps/bps_config.py
- python/lsst/ctrl/bps/transform.py
- python/lsst/ctrl/bps/wms/panda/conf_example/example_panda_SLAC.yaml
- python/lsst/ctrl/bps/wms/panda/panda_service.py
> DM-32594-v23: Remove dependency on inflection in bps_config

- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- python/lsst/ctrl/bps/transform.py
> DM-30266 Update to new QuantumGraph API

- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/wms/panda/edgenode/cmd_line_decoder.py
- python/lsst/ctrl/bps/wms/panda/panda_service.py
- ups/ctrl_bps.table
> DM-32817: Switch from ButlerURI to ResourcePath

- python/lsst/ctrl/bps/bps_utils.py
> DM-33403: Use new location for Packages (now utils)

- doc/changes/DM-32199.feature.rst
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/wms_service.py
> DM-32199-v23: Add WMS check early in submission process.

- bin.src/panda_auth
- config/bps_idf.yaml
- doc/changes/DM-32830.feature.rst
- doc/changes/DM-32830.misc.rst
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/wms/panda/cli/cmd/__init__.py
- python/lsst/ctrl/bps/wms/panda/cli/cmd/panda_auth_commands.py
- python/lsst/ctrl/bps/wms/panda/cli/panda_auth.py
- python/lsst/ctrl/bps/wms/panda/panda_auth_drivers.py
- python/lsst/ctrl/bps/wms/panda/panda_auth_utils.py
- python/lsst/ctrl/bps/wms/panda/panda_service.py
- tests/SConscript
- tests/idds_test.cfg
> DM-32830-v23: Add first version of PanDA authentication tools.

- doc/changes/DM-32199.feature.rst
- doc/changes/DM-32675.feature.rst
- doc/changes/DM-32830.feature.rst
- doc/changes/DM-32830.misc.rst
- doc/lsst.ctrl.bps/CHANGES.rst
> DM-33525 (v23): v23.0.1rc2 release notes

- doc/changes/DM-32199.feature.rst
- doc/changes/DM-32675.feature.rst
- doc/changes/DM-32830.feature.rst
- doc/changes/DM-32830.misc.rst
- doc/lsst.ctrl.bps/CHANGES.rst
> DM-33525: v23.0.1rc2 release notes

- doc/changes/DM-33887.bugfix.rst
- doc/changes/DM-33887.misc.rst
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/wms/htcondor/lssthtc.py
> DM-33887: HTCondor plugin not supporting some htcondor submit file commands

- .github/workflows/build.yaml
- python/lsst/ctrl/bps/drivers.py
- requirements.txt
- setup.cfg
- setup.py
- ups/ctrl_bps.table
> DM-34105: Remove obs_base dependency and add build action

- .github/workflows/build.yaml
- doc/changes/DM-35090.bugfix.rst
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/pre_transform.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- setup.cfg
> DM-35090: Change bps to use DimensionUniverse from repo.

- doc/changes/DM-35066.misc.rst
- python/lsst/ctrl/bps/drivers.py
* Print number of clusters in ClusteredQuantumGraph.
* Print number of jobs (including final) in GenericWorkflow.
> DM-35066: Print sizes of bps graphs.

- .github/workflows/build.yaml
- doc/changes/DM-35144.feature.rst
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/cli/cmd/commands.py
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/ping.py
- python/lsst/ctrl/bps/wms_service.py
- tests/test_cli_commands.py
- tests/test_drivers.py
- tests/test_ping.py
- tests/wms_test_utils.py
> DM-35144: Add ping subcommand.

- doc/changes/DM-35313.bugfix.rst
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/transform.py
- tests/test_transform.py
> DM-35313: Submissions fail when the config defines site-specific job attributes

- .github/workflows/build.yaml
> DM-35598: Run build workflow on tag

- .github/workflows/build.yaml
> DM-35598-hotfix: Fix quotes in PyPi upload GHA

- .github/workflows/build.yaml
> DM-35971: Pytest requires flake<5

- .github/workflows/build.yaml
- README.md
- doc/changes/DM-29575.feature.rst
- doc/changes/DM-29575.misc.rst
- doc/changes/DM-29614.feature.rst
- doc/changes/DM-32657.misc.rst
- doc/changes/DM-33267.misc.rst
- doc/changes/DM-33331.misc.rst
- doc/changes/DM-33521.other.rst
- doc/changes/DM-33887.misc.rst
- doc/changes/DM-34265.bugfix.rst
- doc/changes/DM-34265.misc.rst
- doc/changes/DM-34876.misc.rst
- doc/changes/DM-35066.misc.rst
- doc/changes/DM-35090.bugfix.rst
- doc/changes/DM-35144.feature.rst
- doc/lsst.ctrl.bps/CHANGES.rst
- pyproject.toml
> DM-36034: v24.0.0 release notes

- README.md
- doc/changes/DM-29575.feature.rst
- doc/changes/DM-29575.misc.rst
- doc/changes/DM-29614.feature.rst
- doc/changes/DM-32657.misc.rst
- doc/changes/DM-33267.misc.rst
- doc/changes/DM-33331.misc.rst
- doc/changes/DM-33521.other.rst
- doc/changes/DM-33887.misc.rst
- doc/changes/DM-34265.bugfix.rst
- doc/changes/DM-34265.misc.rst
- doc/changes/DM-34876.misc.rst
- doc/changes/DM-35066.misc.rst
- doc/changes/DM-35090.bugfix.rst
- doc/changes/DM-35144.feature.rst
- doc/lsst.ctrl.bps/CHANGES.rst
- pyproject.toml
> DM-36034: Copy v24.0.0 release notes to main

- doc/lsst.ctrl.bps/quickstart.rst
> Document use of bps report --id.

- doc/changes/DM-37106.bugfix.rst
- python/lsst/ctrl/bps/cli/cmd/commands.py
- tests/test_cli_commands.py
> DM-37106: Remove computeSite arg from all but submit

- doc/changes/DM-37106.bugfix.rst
- doc/conf.py
- python/lsst/ctrl/bps/cli/bps.py
- python/lsst/ctrl/bps/cli/cmd/commands.py
- tests/test_cli_commands.py
> DM-37106-v25: Remove computeSite arg from all but submit

- .pre-commit-config.yaml
- doc/changes/DM-34959.misc.rst
- doc/lsst.ctrl.bps/CHANGES.rst
- python/lsst/ctrl/bps/cli/bps.py
- requirements.txt
- setup.cfg
> DM-38065: v24.1 release notes

- doc/changes/DM-33500.feature.rst
- doc/lsst.ctrl.bps/quickstart.rst
- pyproject.toml
- python/lsst/ctrl/bps/__init__.py
- python/lsst/ctrl/bps/bps_draw.py
- python/lsst/ctrl/bps/bps_reports.py
- python/lsst/ctrl/bps/bps_utils.py
- python/lsst/ctrl/bps/cli/bps.py
- python/lsst/ctrl/bps/cli/opt/option_groups.py
- python/lsst/ctrl/bps/cli/opt/options.py
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/etc/bps_qbb.yaml
- python/lsst/ctrl/bps/ping.py
- python/lsst/ctrl/bps/pre_transform.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- python/lsst/ctrl/bps/transform.py
- python/lsst/ctrl/bps/wms_service.py
> DM-33500: Add QuantumBackedButler option to ctrl_bps

- doc/changes/DM-33500.feature.rst
- doc/changes/DM-34131.doc.rst
- doc/changes/DM-34915.feature.rst
- doc/changes/DM-38307.misc.rst
- doc/changes/DM-38377.bugfix.rst
- doc/changes/DM-38418.api.rst
- doc/changes/DM-38469.removal.rst
- doc/changes/DM-39553.bugfix.rst
- doc/changes/DM-39553.misc.rst
- doc/changes/DM-39949.feature.rst
- doc/changes/DM-40025.other.rst
- doc/lsst.ctrl.bps/CHANGES.rst
- pyproject.toml
- requirements.txt
> DM-40883: Add v26 release notes

- doc/changes/DM-33500.feature.rst
- doc/changes/DM-34131.doc.rst
- doc/changes/DM-34915.feature.rst
- doc/changes/DM-38307.misc.rst
- doc/changes/DM-38377.bugfix.rst
- doc/changes/DM-38418.api.rst
- doc/changes/DM-38469.removal.rst
- doc/changes/DM-39553.bugfix.rst
- doc/changes/DM-39553.misc.rst
- doc/changes/DM-39949.feature.rst
- doc/changes/DM-40025.other.rst
- doc/lsst.ctrl.bps/CHANGES.rst
- pyproject.toml
> DM-40883 (main): Add v26 release notes

- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- tests/cqg_test_utils.py
- tests/qg_test_utils.py
> DM-34340: Adapt to daf_butler API changes.

- .github/workflows/build.yaml
- pyproject.toml
> DM-41904: Add python 3.12

- .github/workflows/build.yaml
- .github/workflows/build_docs.yaml
- .github/workflows/do_not_merge.yaml
- .github/workflows/docstyle.yaml
- .github/workflows/lint.yaml
- doc/changes/DM-43721.bugfix.rst
- python/lsst/ctrl/bps/wms_service.py
- requirements.txt
> DM-43721: Fix compute_site keyword error in submit.

- doc/changes/DM-44200.doc.rst
- doc/lsst.ctrl.bps/quickstart.rst
> DM-44200: In documentation, make section on the automatic retries with requestMemory increase

- doc/changes/DM-44168.misc.rst
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- python/lsst/ctrl/bps/transform.py
> DM-44168: Change bps to use QuantumGraph.pipeline_graph.

- .github/workflows/build.yaml
> DM-44569: Fix build matrix (hotfix)

- doc/changes/DM-44110.misc.rst
- python/lsst/ctrl/bps/bps_config.py
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/wms_service.py
- tests/data/config_with_wms.yaml
- tests/test_bpsconfig.py
- tests/test_drivers.py
- tests/wms_test_utils.py
> DM-44110: Add ability for WMS-specific default configs

- doc/changes/DM-44833.bugfix.rst
- python/lsst/ctrl/bps/bps_config.py
- requirements.txt
- tests/test_bpsconfig.py
> DM-44833: bps can't launch PanDA jobs w/clustering in w24: BPSConfig["cluster"] has `wmsServiceClass` as key

- python/lsst/ctrl/bps/bps_reports.py
> DM-43932: Fix minor typo in output statement.

- doc/changes/DM-42900.misc.rst
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
> DM-42900: Make it simpler to disable output chain updating.

- doc/changes/DM-41672.feature.rst
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/bps_utils.py
- python/lsst/ctrl/bps/cli/opt/option_groups.py
- python/lsst/ctrl/bps/cli/opt/options.py
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
- tests/test_bps_utils.py
> DM-41672: Create WMS-id softlink to submit run directory.

- doc/changes/DM-46513.misc.rst
- doc/lsst.ctrl.bps/quickstart.rst
- pyproject.toml
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
- python/lsst/ctrl/bps/pre_transform.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- tests/cqg_test_utils.py
- tests/qg_test_utils.py
- tests/test_clustered_quantum_graph.py
- tests/test_pre_transform.py
- tests/test_quantum_clustering_funcs.py
> DM-46513: Add QGraph dependencies to dimension clustering.

- doc/changes/DM-43031.doc.rst
- doc/lsst.ctrl.bps/quickstart.rst
> DM-43031: Add a short description of the available BPS plugins

- doc/changes/DM-47625.bugfix.rst
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- tests/cqg_test_utils.py
- tests/test_clustered_quantum_graph.py
> DM-47625: Fix clustering bug causing htc report issues.

- doc/changes/DM-40342.removal.rst
- doc/changes/DM-41672.feature.rst
- doc/changes/DM-42579.misc.rst
- doc/changes/DM-42900.misc.rst
- doc/changes/DM-43985.api.rst
- doc/changes/DM-44110.misc.rst
- doc/changes/DM-44156.misc.rst
- doc/changes/DM-44168.misc.rst
- doc/changes/DM-44200.doc.rst
- doc/changes/DM-44457.misc.rst
- doc/changes/DM-44668.misc.rst
- doc/changes/DM-44833.bugfix.rst
- doc/changes/DM-45635.misc.rst
- doc/changes/DM-46513.misc.rst
- doc/lsst.ctrl.bps/CHANGES.rst
- requirements.txt
> DM-47673: Add v28 release notes

- .github/workflows/build.yaml
- .pre-commit-config.yaml
- doc/changes/DM-40342.removal.rst
- doc/changes/DM-41672.feature.rst
- doc/changes/DM-42579.misc.rst
- doc/changes/DM-42900.misc.rst
- doc/changes/DM-43985.api.rst
- doc/changes/DM-44110.misc.rst
- doc/changes/DM-44156.misc.rst
- doc/changes/DM-44168.misc.rst
- doc/changes/DM-44200.doc.rst
- doc/changes/DM-44457.misc.rst
- doc/changes/DM-44668.misc.rst
- doc/changes/DM-44833.bugfix.rst
- doc/changes/DM-45635.misc.rst
- doc/changes/DM-46513.misc.rst
- doc/lsst.ctrl.bps/CHANGES.rst
- pyproject.toml
> DM-47673: v28 release notes (cherry-picked)

- doc/changes/DM-48245.feature.rst
- python/lsst/ctrl/bps/bps_config.py
- python/lsst/ctrl/bps/transform.py
- tests/test_bpsconfig.py
- tests/test_transform.py
> DM-48245: Fix saving of submit yaml env values to workflow.

- doc/changes/DM-48959.bugfix.rst
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- tests/cqg_test_utils.py
- tests/qg_test_utils.py
- tests/test_clustered_quantum_graph.py
- tests/test_quantum_clustering_funcs.py
> DM-48959: Fix bugs when clustering with findDependencyMethod

- doc/changes/DM-43031.doc.rst
- doc/changes/DM-46307.feature.rst
- doc/changes/DM-47625.bugfix.rst
- doc/changes/DM-48245.feature.rst
- doc/changes/DM-48768.misc.rst
- doc/changes/DM-48872.misc.rst
- doc/changes/DM-48948.misc.rst
- doc/changes/DM-48959.bugfix.rst
- doc/lsst.ctrl.bps/CHANGES.rst
- requirements.txt
> DM-49674 (v29): v29 release notes

- .pre-commit-config.yaml
- doc/changes/DM-43031.doc.rst
- doc/changes/DM-46307.feature.rst
- doc/changes/DM-47625.bugfix.rst
- doc/changes/DM-48245.feature.rst
- doc/changes/DM-48768.misc.rst
- doc/changes/DM-48872.misc.rst
- doc/changes/DM-48948.misc.rst
- doc/changes/DM-48959.bugfix.rst
- doc/lsst.ctrl.bps/CHANGES.rst
> DM-49674: v29 release notes

- doc/changes/DM-46294.feature.rst
- doc/lsst.ctrl.bps/quickstart.rst
- pyproject.toml
- python/lsst/ctrl/bps/bps_utils.py
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- python/lsst/ctrl/bps/tests/gw_test_utils.py
- python/lsst/ctrl/bps/transform.py
- tests/test_bps_utils.py
- tests/test_generic_workflow.py
- tests/test_pre_transform.py
- tests/test_transform.py
> DM-46294:  Add user-defined job ordering

- doc/changes/DM-49744.misc.rst
- python/lsst/ctrl/bps/_exceptions.py
- python/lsst/ctrl/bps/cli/cmd/commands.py
- python/lsst/ctrl/bps/pre_transform.py
- tests/test_cli_commands.py
- tests/test_pre_transform.py
> DM-49744: Return exit code for signal (-9)

- doc/changes/DM-49222.api.rst
- doc/conf.py
- python/lsst/ctrl/bps/__init__.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
> DM-49922-v29:  make _check_clusters_tasks public backport

- doc/changes/DM-49240.feature.rst
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- tests/test_quantum_clustering_funcs.py
> DM-49240: Add partitioning of clusters.

- doc/changes/DM-50243.doc.rst
- doc/lsst.ctrl.bps/quickstart.rst
> DM-50243: Add logging instructions to documentation.

- doc/changes/DM-50294.rst
- python/lsst/ctrl/bps/pre_transform.py
- tests/test_pre_transform.py
> DM-50294: Decrease write buffering for execute function.

- doc/changes/DM-49747.misc.rst
- python/lsst/ctrl/bps/generic_workflow.py
- tests/test_generic_workflow.py
> DM-49747: Check group config's job label list.

- doc/changes/DM-50619.feature.rst
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/cli/cmd/commands.py
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/report.py
- python/lsst/ctrl/bps/status.py
- python/lsst/ctrl/bps/wms_service.py
- tests/test_cli_commands.py
- tests/test_drivers.py
- tests/test_status.py
- tests/wms_test_utils.py
> DM-50619: Add subcommand for quickly printing run status.

- .github/workflows/build_docs.yaml
- doc/changes/DM-46294.feature.rst
- doc/changes/DM-49222.api.rst
- doc/changes/DM-49240.feature.rst
- doc/changes/DM-49744.misc.rst
- doc/changes/DM-49747.misc.rst
- doc/changes/DM-50243.doc.rst
- doc/changes/DM-50294.rst
- doc/changes/DM-50498.misc.rst
- doc/changes/DM-50619.feature.rst
- doc/lsst.ctrl.bps/CHANGES.rst
> DM-51073: v29.1 release notes

- doc/changes/DM-48479.feature.rst
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/construct.py
- python/lsst/ctrl/bps/transform.py
- tests/test_construct.py
> DM-48479: Provide support for file transferring when using bps submitcmd

- config/no_execution_butler.yaml
- doc/changes/DM-52339.misc.md
- doc/conf.py
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/bps_utils.py
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
- python/lsst/ctrl/bps/pre_transform.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- python/lsst/ctrl/bps/transform.py
- tests/cqg_test_utils.py
- tests/qg_test_utils.py
- tests/test_clustered_quantum_graph.py
- tests/test_pre_transform.py
> DM-52339: use new QG class and format

- doc/changes/DM-52791.bug.rst
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/report.py
> DM-52791: Pass return_exit_codes to plugin's report method.
