lsst/ctrl_bps

- python/lsst/ctrl/bps/bps_config.py
- python/lsst/ctrl/bps/bps_core.py
After recent code changes in other ticket, bpsub started printing
bunches of warning messages like the following:
WARNING::10/02/2020 18:31:00::Missing search section...
This was due to sub-configs being created with same top-level
search_order.  Modified BpsConfig to take search_order as an
optional argument and fixed creation of object in bps_core.py
to pass the BPS search_order into the constructor.
Also fixed the following while in the bps_config.py code:
* Fixed bug when printing an error message that assumed an
internal value existed (current).
* Fixed function signatures for __getitem__ and __contains__.
* Added info to search docstring about valid keys for the
search options.
> DM-27049: Fix BpsConfig after changes caused warnings

- python/lsst/ctrl/bps/bps_core.py
Prior to running actual Quanta, an intialization step should be run
to save config files, software versions, schemas, etc.  Previously,
there was a single job per PipelineTask in the pipeline that called
`pipetask --initonly`.  The work in this ticket changed that to be a
single job per submission (i.e., once for entire QuantumGraph).
Note:  This code change requires removing --extend-run from the
runQuantumArgs entry for pipetask_init in user BPS configs.
Review Note:  Did not write unit test for these code changes as
bps_core.py's code will be reorganized in next ticket (DM-27039).
> DM-26385: Perform pipetask --initonly in a single job.

- doc/lsst.ctrl.bps/pipelines_check.yaml
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/pre_transform.py
- python/lsst/ctrl/bps/prepare.py
- python/lsst/ctrl/bps/transform.py
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/wms/htcondor/lssthtc.py
- python/lsst/ctrl/bps/wms/pegasus/pegasus_service.py
requestMemory problem
* Code was expecting request_memory instead of requestMemory
in the yaml file.  Fixed to expect requestMemory.
* Code expected integers, but example config still showed as
string (2GB).  Fixed example in docs.
* Code got back string from BpsConfig and needed to cast to int.
* Pegasus plugin was missing code to use these values.
matching glidein nodes
Code existed in the Pegasus plugin and works.  Added code to
the HTCondor plugin to allow pass through values.  Added
example config lines to the docs.
The --init-only job did not have any code to pick up either of
these settings, so added it.
Minor changes:
* Moved sample config from docs to separate file that is included
in docs.  Easier to copy it for use that way.
* Fixed other snake case config keys to camel case …
> DM-27575: fix requestMemory and matching glidein nodes.

- doc/lsst.ctrl.bps/pipelines_check.yaml
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/submit.py
- ups/ctrl_bps.table
Update code to use new Instrument.makeCollectionTimestamp()
when creating the timestamp for use in naming output collections.
Also update collection names in the sample yaml provided in
the docs.  Note:  This commit only changed the output collection,
because at this time pipelines_check has not been changed.  When
pipelines_check has been changed to use the "HSC/defaults"
collection, the example's input collection should also be changed.
> DM-27147: Update ctrl_bps to use new timestamp format.

- doc/conf.py
- doc/lsst.ctrl.bps/index.rst
- doc/lsst.ctrl.bps/pipelines_check.yaml
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/wms/htcondor/lssthtc.py
- tests/test_lssthtc.py
The HTCondor plugin's code assumed that attribute value was a string.  But Walltime on NCSA's DAC cluster needs to be an integer.  So this ticket fixed the plugin code.   Also some unrelated doc changes.
> DM-28929: Allow non-string HTCondor attributes 

- doc/lsst.ctrl.bps/pipelines_check.yaml
- doc/lsst.ctrl.bps/quickstart.rst
Using both --output and --output-run in the runQuantumCommands
will have pipetask create the Chained collection and all compute
jobs will share the same Run collection.  Modified example yaml
file and updated quickstart guide.
Note:  Overall documentation improvement covered in other ticket,
so just followed current documentation style for these changes.
> DM-28960: Change example and doc to get Chained collection.

- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/transform.py
- python/lsst/ctrl/bps/wms/htcondor/lssthtc.py
This is the short-term fix ticket that fixes a bug keeping htcondor jobs from using the qgraph file it staged.  With the bug, it worked when there was a shared filesystem such that the job could access it in the submit location.  The long-term changes to not put it in the command line at all in the GenericWorkflow, but instead leaving it for the WMS plugin to handle is in a different ticket.  Tested with htcondor and pegasus plugins.  
While discussing this change with the folks who needed it because they don't have a shared filesystem, discovered that setting the environment in the htcondor section of the BPS yaml also wasn't working.  Since simple fix, just made the change in this ticket too.
> DM-27666: Remove path from qgraph filename in command line.

- python/lsst/ctrl/bps/report.py
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/wms/htcondor/lssthtc.py
Fixed the order of the reporting of pipelineTasks to be consistent between calls.  Also fixed the reporting in the summary of running jobs (would always be 0).  And because jobs were falling off of the NCSA history logs so fast, bps report was treating those forgotten jobs as unready.  Fixed it to use more information from the submit directory (but it is slower for large DAGs).
Also tweaked some of the column widths (and truncating too long values) as well as switched init to pipetaskInit in report to match submit yaml.
> DM-27570: Fix bps report ordering and history-loss issues.

- python/lsst/ctrl/bps/wms/panda/edgenode/sw_runner
The updated code reads credentials from the Google Secrets mounted to the container and exports them just before the payload application starts
> Google secrets in files on a volume mounted to container

- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/cancel.py
- python/lsst/ctrl/bps/cli/cmd/__init__.py
- python/lsst/ctrl/bps/cli/cmd/commands.py
- python/lsst/ctrl/bps/cli/script/cli_cancel.py
- python/lsst/ctrl/bps/cli/script/report.py
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/wms/htcondor/lssthtc.py
- python/lsst/ctrl/bps/wms/pegasus/pegasus_service.py
- python/lsst/ctrl/bps/wms_service.py
Added cancel subcommand and support in HTCondor and Pegasus plugins.
(Also removed a couple of unnecessary lines from report.py found while looking to see if could reuse code.)
> DM-27676: Add ability to remove submitted runs.

- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/bps_utils.py
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/pre_transform.py
- python/lsst/ctrl/bps/prepare.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- python/lsst/ctrl/bps/transform.py
pipetask has ability to take full QuantumGraph and list of node numbers to run.  Code for this ticket added the ability to for bps to handle that as well.  
QuantumGraph also had Uri versions of save and load functions added a while back.  Switched bps code to use those.
Calling subset to create the ClusteredQuantumGraph runs longer and uses more memory than just storing a list of NodeIds.  So changed the internal representation.   This change removed dataIds from appearing in the GenericWorkflow which was being used by someone to do late job resource estimation.  While longer term this better job resource estimation should go earlier in the process and not in a WMS plugin, decided to try to provide this information until the earlier estimation capabilities are in place.  To this end, job …
> DM-27675: Add ability to pass single large QuantumGraph to jobs.

- python/lsst/ctrl/bps/quantum_clustering_funcs.py
Code assumed dataId.to_simple() would return a dict.  The
type of dataId changed so this is no longer true.
> DM-29953: Fix TypeError on dataId.

- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
Just an omission in original plugin coding.  Added lines so that request_cpus is added to the HTCondor job submit script.  Tested Pegasus plugin.  It worked as is.
> Fix requestCpus in HTCondor plugin.

- doc/lsst.ctrl.bps/pipelines_check.yaml
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/bps_config.py
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/prepare.py
- python/lsst/ctrl/bps/transform.py
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/wms/pegasus/pegasus_service.py
- tests/data/config.yaml
- tests/test_bpsconfig.py
Postpone creation of command line to the plugin.  Added special GenericWorkflowJob cmdline syntax placeholders <ENV:name> and <FILE:name> as these are easier to distinguish from the other normal f-string placeholders.
> DM-29007: Lazy command line creation.

- .gitattributes
- doc/changes/DM-28653.feature.rst
- doc/changes/DM-29893.feature.rst
- doc/changes/README.rst
- doc/lsst.ctrl.bps/pipelines_check.yaml
- doc/lsst.ctrl.bps/pipelines_check_execution_butler.yaml
- doc/lsst.ctrl.bps/quickstart.rst
- etc/bps_defaults.yaml
- python/lsst/ctrl/bps/bps_config.py
- python/lsst/ctrl/bps/bps_utils.py
- python/lsst/ctrl/bps/cli/cmd/commands.py
- python/lsst/ctrl/bps/cli/opt/arguments.py
- python/lsst/ctrl/bps/cli/opt/option_groups.py
- python/lsst/ctrl/bps/cli/opt/options.py
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/pre_transform.py
- python/lsst/ctrl/bps/prepare.py
- python/lsst/ctrl/bps/submit.py
- python/lsst/ctrl/bps/transform.py
- python/lsst/ctrl/bps/wms/htcondor/final_post.sh
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/wms/htcondor/lssthtc.py
- python/lsst/ctrl/bps/wms/panda/cmd_line_embedder.py
- python/lsst/ctrl/bps/wms/panda/idds_tasks.py
- python/lsst/ctrl/bps/wms/panda/panda_service.py
- python/lsst/ctrl/bps/wms/pegasus/pegasus_service.py
- tests/test_pre_transform.py
Creating a draft pull request for the initial changes.
> Initial changes to support execution butler.

- .github/pull_request_template.md
- doc/changes/DM-31884.feature.rst
- python/lsst/ctrl/bps/cli/bps.py
> DM-31384: Add --log-label to bps command

- doc/changes/DM-31841.bugfix.rst
- doc/changes/DM-31841.feature.rst
- doc/lsst.ctrl.bps/execution_butler.yaml
- doc/lsst.ctrl.bps/pipelines_check.yaml
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/transform.py
- python/lsst/ctrl/bps/wms/htcondor/lssthtc.py
> DM-31841: The queue parameter submitted on per task level is not available in the GenericWorkflowJob

- python/lsst/ctrl/bps/wms/panda/conf_example/pipelines_check_execution_butler_idf.yaml
- python/lsst/ctrl/bps/wms/panda/conf_example/pipelines_check_idf.yaml
- python/lsst/ctrl/bps/wms/panda/edgenode/cmd_line_decoder.py
- python/lsst/ctrl/bps/wms/panda/idds_tasks.py
- python/lsst/ctrl/bps/wms/panda/panda_service.py
> DM-31900: Compute site changes for PanDA

- doc/changes/DM-31944.bugfix.rst
- doc/changes/DM-31944.misc.rst
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/wms/htcondor/lssthtc.py
Since I was in that plugin, I also tried out SET_JOB_ATTR to save bps_* attributes to .dag file so that they still are in the classad after a manual condor_submit_dag restart.
> DM-31944: Fix HTCondor plugin splitting single concurrency_limit

- doc/changes/DM-31970.bugfix.rst
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
Both of these are backwards compatibility issues caused by DM-31887 changes.
> DM-31970:  Fix AttributeError and bps report of older runs.

- doc/changes/DM-32201.bugfix.rst
- doc/changes/DM-32201.misc.rst
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
when output collection has period.
> DM-32201: Fix execution butler with HTCondor plugin bug

- doc/changes/DM-32220.bugfix.rst
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
- python/lsst/ctrl/bps/wms/htcondor/lssthtc.py
> DM-32220: Disable HTCondor auto-detection of output files

- python/lsst/ctrl/bps/wms/panda/edgenode/cmd_line_decoder.py
> DM-32435 Implemented propagation of pipetask kill by signal

- config/bps_idf.yaml
- doc/changes/DM-32594.other.rst
- python/lsst/ctrl/bps/bps_config.py
- python/lsst/ctrl/bps/transform.py
- python/lsst/ctrl/bps/wms/panda/conf_example/example_panda_SLAC.yaml
- python/lsst/ctrl/bps/wms/panda/panda_service.py
Rolled back changes in BpsConfig that were added for flexibility when
looking up config values (e.g., snake case keys will no longer match
camel case keys nor will either match lower case keys).
> DM-32594: Roll back BpsConfig changes that added dependence on inflection package.

- doc/changes/DM-32657.misc.rst
- python/lsst/ctrl/bps/bps_utils.py
- python/lsst/ctrl/bps/drivers.py
> DM-32657: Abort bps submission if submit-side run directory already exists

- doc/changes/DM-32968.misc.rst
- python/lsst/ctrl/bps/wms/htcondor/htcondor_service.py
> DM-32968: Job put on hold if exit with signal 11

- bin.src/panda_auth
- config/bps_idf.yaml
- doc/changes/DM-32830.feature.rst
- doc/changes/DM-32830.misc.rst
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/wms/panda/cli/cmd/__init__.py
- python/lsst/ctrl/bps/wms/panda/cli/cmd/panda_auth_commands.py
- python/lsst/ctrl/bps/wms/panda/cli/panda_auth.py
- python/lsst/ctrl/bps/wms/panda/panda_auth_drivers.py
- python/lsst/ctrl/bps/wms/panda/panda_auth_utils.py
- python/lsst/ctrl/bps/wms/panda/panda_service.py
- tests/SConscript
- tests/idds_test.cfg
> DM-32830: Add first version of PanDA authentication tools.

- doc/changes/DM-34265.bugfix.rst
- doc/changes/DM-34265.misc.rst
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- tests/cqg_test_utils.py
- tests/qg_test_utils.py
- tests/test_quantum_clustering_funcs.py
> DM-34265: Abort clustering if Quantum missing value.

- doc/changes/DM-34876.misc.rst
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/bps_config.py
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/transform.py
- tests/cqg_test_utils.py
- tests/test_transform.py
Added cloud to the submit yaml as a config section, specify which
cloud via computeCloud.  GenericWorkflowJob now has compute_cloud.
> DM-34876: Add cloud concept to bps.

- requirements.txt
- setup.cfg
> DM-35199: Fix python package names

- doc/changes/DM-34959.misc.rst
- python/lsst/ctrl/bps/generic_workflow.py
> DM-34959: Replace read_gpickle and write_gpickle in GenericWorkflow

- doc/changes/DM-37044.feature.rst
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/cli/cmd/commands.py
- python/lsst/ctrl/bps/cli/opt/options.py
- python/lsst/ctrl/bps/drivers.py
- tests/test_cli_commands.py
> DM-37044: Add ability to specify computeSite on the CLI

- doc/changes/DM-34915.feature.rst
- python/lsst/ctrl/bps/generic_workflow.py
- tests/test_generic_workflow.py
> DM-34915: Add traversal of GenericWorkflow by job label.

- doc/changes/DM-34959.misc.rst
- python/lsst/ctrl/bps/generic_workflow.py
> DM-34959-v24: backport removal of deprecated networkx interfaces

- .github/workflows/build_docs.yaml
- doc/changes/DM-34959.misc.rst
- doc/changes/DM-35293.feature.rst
- doc/changes/DM-35313.bugfix.rst
- doc/changes/DM-37044.feature.rst
- doc/changes/DM-37106.bugfix.rst
- doc/lsst.ctrl.bps/CHANGES.rst
- python/lsst/ctrl/bps/bps_reports.py
> DM-38065: v25 release notes on main

- doc/changes/DM-38418.api.rst
- python/lsst/ctrl/bps/bps_config.py
- tests/test_bpsconfig.py
> DM-38418: Override get method in BpsConfig to make default value parameter work

- doc/changes/DM-38469.removal.rst
- doc/changes/README.rst
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/pre_transform.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
Call QuantumGraph.loadUri() directly as passing of butler repository's DimensionUniverse is no longer needed.
> DM-38469: Remove read_quantum_graph method.

- doc/changes/DM-38377.bugfix.rst
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- python/lsst/ctrl/bps/transform.py
- tests/cqg_test_utils.py
- tests/test_clustered_quantum_graph.py
- tests/test_generic_workflow.py
- tests/test_quantum_clustering_funcs.py
- tests/test_transform.py
> DM-38377: Fix label order bugs found by rescue workflows.

- doc/changes/DM-38307.misc.rst
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
> DM-38307: Enable simpler yaml when no output collection.

- tests/qg_test_utils.py
The tests can use arbitrary run name, but it needs some care to properly connect intermediate refs.
> DM-39123: Update graph-producing code to use resolved refs

- .github/workflows/build.yaml
- .github/workflows/build_docs.yaml
- .github/workflows/lint.yaml
- .pre-commit-config.yaml
- doc/conf.py
- doc/lsst.ctrl.bps/quickstart.rst
- pyproject.toml
- python/lsst/ctrl/bps/bps_config.py
- python/lsst/ctrl/bps/bps_reports.py
- python/lsst/ctrl/bps/cli/bps.py
- python/lsst/ctrl/bps/cli/cmd/commands.py
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/wms_service.py
- tests/qg_test_utils.py
- tests/test_bps_utils.py
- tests/test_bpsconfig.py
- tests/test_clustered_quantum_graph.py
- tests/test_drivers.py
- tests/test_generic_workflow.py
- tests/test_ping.py
- tests/test_pre_transform.py
- tests/test_quantum_clustering_funcs.py
- tests/test_transform.py
- tests/wms_test_utils.py
> DM-39857: Turn off pytest-flake8 and add ruff configuration

- python/lsst/ctrl/bps/bps_config.py
Config supports reading of package resources directly so there is no need to find the local path to the resources in BPS itself. Also remove the __init__.py since the resources do not need it.
> DM-39898: Use ResourcePath to read the bps defaults

- doc/changes/DM-39949.feature.rst
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
> DM-39949: Expand quantum cluster dims: include implied dims

- .github/workflows/do_not_merge.yaml
- .github/workflows/rebase_checker.yaml
- doc/changes/DM-39553.bugfix.rst
- doc/changes/DM-39553.misc.rst
- doc/lsst.ctrl.bps/pipelines_check.yaml
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/etc/bps_qbb.yaml
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/transform.py
> DM-39553: Misc updates discovered when enabling QBB with ctrl_bps_panda

- tests/test_bpsconfig.py
Config is lifted so no need to specify the path including core.
> DM-41043: Fix import of Config from butler

- doc/changes/DM-41561.doc.rst
- doc/lsst.ctrl.bps/quickstart.rst
> DM-41561: Make bps restart accept various types of run IDs

- doc/changes/DM-41543.feature.rst
- python/lsst/ctrl/bps/bps_reports.py
- python/lsst/ctrl/bps/cli/cmd/commands.py
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/report.py
- python/lsst/ctrl/bps/wms_service.py
- tests/test_report.py
Preliminary draft version to run some things past Michelle since it is my first significant contribution to BPS code base.
> DM-41543: Adds Reporting Exit Code Information to bps report

- .github/workflows/docstyle.yaml
- .pre-commit-config.yaml
- pyproject.toml
- python/lsst/ctrl/bps/bps_draw.py
- python/lsst/ctrl/bps/bps_reports.py
- python/lsst/ctrl/bps/cli/bps.py
- python/lsst/ctrl/bps/cli/opt/option_groups.py
- python/lsst/ctrl/bps/cli/opt/options.py
- python/lsst/ctrl/bps/clustered_quantum_graph.py
- python/lsst/ctrl/bps/constants.py
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/generic_workflow.py
- python/lsst/ctrl/bps/ping.py
- python/lsst/ctrl/bps/quantum_clustering_funcs.py
- python/lsst/ctrl/bps/report.py
- python/lsst/ctrl/bps/restart.py
- python/lsst/ctrl/bps/submit.py
- python/lsst/ctrl/bps/transform.py
- python/lsst/ctrl/bps/wms_service.py
- tests/cqg_test_utils.py
- tests/qg_test_utils.py
- tests/test_clustered_quantum_graph.py
- tests/test_ping.py
- tests/test_report.py
- tests/test_transform.py
@mxk62 can you please take a look at this. No need to check every doc string. What I especially want you to do is look at the changes to the dataclasses that I made to enable slots. This lets us remove a lot of code that wasn't needed since 3.10 came out.
> DM-42116: Validate docstrings

- doc/changes/DM-42206.bugfix.rst
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
> DM-42206: Remove --transfer-dimensions from final job.

- doc/changes/DM-44156.misc.rst
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
> DM-44156: Include memoryLimit in BPS defaults

- doc/changes/DM-43985.api.rst
- python/lsst/ctrl/bps/bps_reports.py
- python/lsst/ctrl/bps/drivers.py
- python/lsst/ctrl/bps/report.py
- tests/test_report.py
- tests/wms_test_utils.py
> DM-43985: Create bps report API

- doc/changes/DM-44668.misc.rst
- doc/lsst.ctrl.bps/quickstart.rst
- python/lsst/ctrl/bps/etc/bps_defaults.yaml
- python/lsst/ctrl/bps/generic_workflow.py
- requirements.txt
Updated retryUnlessExit to allow multiple exit codes and added description to documentation.
> DM-44668: Updated allowed types for retryUnlessExit and docs.

- doc/changes/DM-48768.misc.rst
- python/lsst/ctrl/bps/bps_reports.py
- tests/test_report.py
> DM-48768: Use Table.pformat() instead of the deprecated Table.pformat_all() in ctrl_bps

- doc/changes/DM-48872.misc.rst
- python/lsst/ctrl/bps/bps_reports.py
- tests/test_report.py
> DM-48872: Restore the previous behavior of bps report in rubin-env-9

- tests/test_pre_transform.py
Some unit tests were matching patterns containing full paths against messages that should be logged. I replaced them with simple tests for string inclusion to avoid issues with special characters these path may contain.
> DM-49744-hotfix: Return exit code for signal (-9)

- doc/changes/DM-50498.misc.rst
- python/lsst/ctrl/bps/transform.py
- tests/test_transform.py
> DM-50498: Ensure all job environment values are strings.
